name: Deploy Local Terraform

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    # Run on PR open/update OR when merged
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve
- name: Upload Terraform State
  uses: actions/upload-artifact@v4
  with:
    name: tfstate
    path: terraform.tfstate
